version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "deps"
      - "deps:actions"
    commit-message:
      prefix: "deps(actions)"
      include: "scope"
    groups:
      actions-core:
        patterns:
          - "actions/*"
        update-types:
          - "minor"
          - "patch"
      actions-third-party:
        patterns:
          - "*"
        exclude-patterns:
          - "actions/*"
        update-types:
          - "minor"
          - "patch"
