verbose = true
no_progress = true
exclude_mail = true
include_fragments = true
accept = [200, 204, 301, 302, 303, 307, 308]
timeout = 20
max_redirects = 5
retry_wait_time = 2
retry_count = 2
user_agent = "heimgewebe-linkcheck (+https://github.com/heimgewebe/metarepo)"

# Optional: Domains lassen sich hier ausschließen, falls einzelne Ziele drosseln.
# exclude = ["https://raw.githubusercontent.com/heimgewebe/.*/large-assets/.*"]

[[inputs]]
path = "README.md"

[[inputs]]
path = "docs"
