name: ci-shellcheck
permissions:
  contents: read

defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}

on:
  push:
    paths:
      - '**/*.sh'
      - '.github/workflows/ci-shellcheck.yml'
  pull_request:
    paths:
      - '**/*.sh'
      - '.github/workflows/ci-shellcheck.yml'
  workflow_dispatch:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@a5ac7e54b508e203cb80d02e7a928114292adde3 # actions/checkout@v4

      - name: Install ShellCheck
        run: sudo apt-get update -yqq && sudo apt-get install -yqq shellcheck

      - name: Run ShellCheck on tracked scripts
        run: |
          set -euo pipefail

          mapfile -t scripts < <(git ls-files '*.sh')

          if [ "${#scripts[@]}" -eq 0 ]; then
            echo "No shell scripts found."
            exit 0
          fi

          shellcheck "${scripts[@]}"
