name: docs-linkcheck
permissions:
  contents: read

defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}

concurrency:
  group: docs-linkcheck-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  lychee:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4 # v4 (major tag)
      - name: Cache lychee URL state
        uses: actions/cache@v4 # v4 (major tag)
        with:
          path: ~/.cache/lychee
          key: ${{ runner.os }}-lychee-${{ hashFiles('.lychee.toml', 'README.md', 'docs/**/*.md') }}
          restore-keys: |
            ${{ runner.os }}-lychee-
      - name: Check documentation links (uses .lychee.toml)
        uses: lycheeverse/lychee-action@v2.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LYCHEE_CACHE_DIR: ~/.cache/lychee
        with:
          args: --config .lychee.toml --statistics
          fail: true
