name: impact-guard

on:
  pull_request:
    paths:
      - "contracts/*.schema.json"
      - "repos.yml"
      - "metarepo_tools/impact_guard.py"
      - ".github/workflows/impact-check.yml"
  push:
    paths:
      - "contracts/*.schema.json"
      - "repos.yml"
      - "metarepo_tools/impact_guard.py"
      - ".github/workflows/impact-check.yml"
  workflow_dispatch:

permissions:
  contents: read
concurrency:
  group: impact-guard-${{ github.ref }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}

jobs:
  impact:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Detect changes (contracts + manifest)
        id: changed
        uses: tj-actions/changed-files@v45
        with:
          files: |
            contracts/*.schema.json
            repos.yml

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f pyproject.toml ] || [ -f setup.py ]; then
            python -m pip install .
          else
            python -m pip install pyyaml || true
          fi

      - name: Run impact guard analysis (always)
        run: |
          if [ -f pyproject.toml ] || [ -f setup.py ]; then
            set -- python -m metarepo_tools.impact_guard
          else
            set -- python metarepo_tools/impact_guard.py
          fi
          "$@" \
            --contracts-dir contracts \
            --manifest repos.yml \
            --graph-out reports/impact/impact-graph.mmd \
            --report-out reports/impact/impact-report.md \
            --json-out reports/impact/impact-report.json \
            $(printf '%s\n' "${{ steps.changed.outputs.all_changed_files }}" | tr '\n' ' ')

      - name: Publish summary
        run: cat reports/impact/impact-report.md >> "$GITHUB_STEP_SUMMARY"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: impact-guard-report
          path: |
            reports/impact/impact-report.md
            reports/impact/impact-report.json
            reports/impact/impact-graph.mmd
          retention-days: 7
