name: reusable-ci

permissions:
  contents: read

defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}

on:
  workflow_call:
    inputs:
      run_lint:
        description: "Run linting (default: true)"
        required: false
        default: true
        type: boolean
      run_tests:
        description: "Run tests (default: true)"
        required: false
        default: true
        type: boolean

jobs:
  reusable-ci:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e54b508e203cb80d02e7a928114292adde3 # actions/checkout@v4

      - name: Setup Just
        uses: extractions/setup-just@v2

      - name: Install Dependencies (optional)
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f package.json ]; then npm ci; fi

      - name: Skip Justfile-dependent steps when missing Justfile
        if: ${{ hashFiles('Justfile') == '' }}
        run: echo "::notice::Kein Justfile gefunden – Just-Schritte übersprungen."

      - name: Lint
        if: ${{ inputs.run_lint == true && hashFiles('Justfile') != '' }}
        run: |
          if just --show lint >/dev/null 2>&1; then
            just lint
          else
            echo "::notice::Kein Lint-Target gefunden – übersprungen."
          fi

      - name: Test
        if: ${{ inputs.run_tests == true && hashFiles('Justfile') != '' }}
        run: |
          if just --show test >/dev/null 2>&1; then
            just test
          else
            echo "::notice::Kein Test-Target gefunden – übersprungen."
          fi

      - name: Summary
        run: echo "✅ reusable-ci completed successfully."
