name: validate-templates
permissions:
  contents: read
concurrency:
  group: validate-templates-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}
on:
  push:
    paths:
      - 'templates/**'
      - 'scripts/**'
      - 'repos.yml'
      - '.github/workflows/validate-templates.yml'
  pull_request:
    paths:
      - 'templates/**'
      - 'scripts/**'
      - 'repos.yml'
      - '.github/workflows/validate-templates.yml'

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4 # actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@b55428b3186412ab7664c751e0b43c43eb1cc02a # actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install pyyaml
      - name: Run local validation script
        run: ./.github/workflows/validate-local.sh
