name: validate-templates
on:
  push:
    paths:
      - 'templates/**'
      - 'scripts/**'
      - 'repos.yml'
      - '.github/workflows/validate-templates.yml'
  pull_request:
    paths:
      - 'templates/**'
      - 'scripts/**'
      - 'repos.yml'
      - '.github/workflows/validate-templates.yml'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check YAMLs
        run: |
          pipx install yq || true
          find . -type f -name '*.yml' -o -name '*.yaml' | xargs -r -I{} python -c "import yaml,sys; yaml.safe_load(open('{}'))"
      - name: List templates
        run: |
          find templates -type f | sort
